name: created

on:
  release:
    types: [created]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo variables
        run: |
          echo "tag name: ${{ github.event.release.tag_name }}"
