name: Deploy

on:
  release:
    types: [created, edited, deleted]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo variables
        run: |
          echo "tag name: ${{ toJson(github.event) }}"
