name: Deploy

on:
  release:
    types: [created, edited, deleted]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Action name
        run: echo "${{ github.event.action }}"
      - name: Check pre-release
        run: echo "${{ github.event.release.prerelease }}"
      - id: get_release
        uses: joutvhu/get-release@v1
        with:
          latest: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get release
        run: echo "${{ toJson(steps.get_release.outputs) }}"